# Generated by Django 4.1.5 on 2023-02-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
    ]
