# Generated by Django 4.1.5 on 2023-02-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
    ]
